##  Makefile for @{NAME}
##  Usage: make (|build|clean|install|load|targets)

APP = @{NAME}

##  Production settings, override in config/local.mk

MEM = 512
APP_USER = @{NAME}
APP_GROUP = @{NAME}
WEB_USER = @{NAME}
WEB_GROUP = _nginx

include lib/rol/server/app.mk
